apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:$COMMIT_SHA
          ports:
            - containerPort: 8080
