steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'us-central1-docker.pkg.dev/prajesh/my-repo/my-app:$COMMIT_SHA', 
      '.'
    ]

  # Step 2: Push the Docker image to Google Cloud Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/prajesh/my-repo/my-app:$COMMIT_SHA'
    ]

images:
  - 'us-central1-docker.pkg.dev/prajes/my-repo/my-app:$COMMIT_SHA'
