steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app-1'
      - '--image'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated'

  # Step 4: Check the deployed service status and rollback if necessary
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Send a request to the Cloud Run service and capture the HTTP status code
        response=$(curl -o /dev/null -s -w "%{http_code}\n" https://dev-gf22ekzyxq-el.a.run.app)

        # Check the status code and take action
        if [ "$response" -eq 200 ]; then
          echo "Deployment successful! Service is healthy."
        elif [ "$response" -eq 500 ]; then
          echo "Deployment failed with status 500! Rolling back..."

          # Get the list of all releases and check their statuses
          releases=$(gcloud deploy releases list \
            --delivery-pipeline=my-run-demo-app-1 \
            --region=asia-south1 \
            --format="value(name)")

          last_successful_release=""

          for release in $releases; do
            release_status=$(gcloud deploy releases describe $release \
              --delivery-pipeline=my-run-demo-app-1 \
              --region=asia-south1 \
              --format="value(renderState)")

            if [ "$release_status" == "SUCCEEDED" ]; then
              last_successful_release=$release
              break
            fi
          done

          if [ -z "$last_successful_release" ]; then
            echo "No previous successful release found. Rollback not possible."
            exit 1
          fi

          # Re-deploy the last successful release
          gcloud deploy releases create $last_successful_release-rollback-$SHORT_SHA \
            --delivery-pipeline=my-run-demo-app-1 \
            --to-target=dev \
            --region=asia-south1 \
            --file=cloud-deploy/dev/pipeline.yaml \
            --skaffold-file=skaffold.yaml

        else
          echo "Deployment failed with status $response! Exiting."
          exit 1
        fi

images:
  - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'

logsBucket: 'gs://cloud-build-02'
