steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'asia-south1-docker.pkg.dev/prajesh/my-app2/my-app-1:$COMMIT_SHA', 
      '.'
    ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'asia-south1-docker.pkg.dev/prajesh/my-app2/my-app-1:$COMMIT_SHA'
    ]

  # Step 3: Create a Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'deploy', 
      'releases', 
      'create', 
      'my-app-release-$COMMIT_SHA',  # Release name
      '--delivery-pipeline', 
      'my-app-pipeline', 
      '--region', 
      'asia-south1',
      '--images',
      'my-app-1=us-central1-docker.pkg.dev/prajesh/my-app2/my-app-1:$COMMIT_SHA'
    ]

  # Step 4: Deploy the image to Cloud Run using Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 
      'deploy', 
      'my-app-1',  
      '--image', 
      'asia-south1-docker.pkg.dev/prajesh/my-app2/my-app-1:$COMMIT_SHA', 
      '--platform',
      'managed',
      '--region',
      'asia-south1',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-02/my-app-1:$COMMIT_SHA'

logsBucket: 'gs://cloud-build-03'
