steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'

  # Step 3: Trigger Cloud Deploy
  - name: 'google/cloud-sdk:latest'
    id: Trigger Cloud Deploy
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        gcloud config set deploy/region asia-south1
        gcloud deploy apply --file cloud-deploy/dev/pipeline.yaml
        gcloud deploy apply --file cloud-deploy/dev/target.yaml
        gcloud deploy releases create my-app-1-$SHORT_SHA \
                            --delivery-pipeline=my-run-demo-app-1 \
                            --skaffold-file=skaffold.yaml

  # Step 4: Describe the release and check for failure
  - name: 'google/cloud-sdk:latest'
    id: Describe Cloud Deploy Release
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        RENDER_STATE=$(gcloud deploy releases describe "my-app-1-$SHORT_SHA" \
          --delivery-pipeline="my-run-demo-app-1" \
          --region="asia-south1" \
          --format "yaml(renderState)" \
          | awk '{print $2}')
        echo "Render State: $RENDER_STATE"
        if [[ "$RENDER_STATE" != "SUCCEEDED" ]]; then
          echo "Deployment failed, rolling back to the previous version..."
          PREV_RELEASE=$(gcloud deploy releases list \
            --delivery-pipeline=my-run-demo-app-1 \
            --region=asia-south1 \
            --format="value(name)" \
            --limit=2 | tail -n1)
          echo "Rolling back to $PREV_RELEASE"
          gcloud deploy targets rollback dev \
            --delivery-pipeline=my-run-demo-app-1 \
            --region="asia-south1" \
            --release="$PREV_RELEASE"
        else
          echo "Deployment succeeded."
        fi

images:
  - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'

logsBucket: 'gs://cloud-build-02'
