steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'

  # Step 3: Trigger Cloud Deploy
  - name: 'google/cloud-sdk:latest'
    id: Trigger Cloud Deploy
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        gcloud config set deploy/region asia-south1
        gcloud deploy apply --file cloud-deploy/dev/pipeline.yaml
        gcloud deploy apply --file cloud-deploy/dev/target.yaml
        gcloud deploy releases create my-app-1-$SHORT_SHA \
                            --delivery-pipeline=my-run-demo-app-1 \
                            --skaffold-file=skaffold.yaml

  # Step 4: Describe the release
  - name: 'google/cloud-sdk:latest'
    id: Describe Cloud Deploy Release
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'describe'
      - 'my-app-1-$SHORT_SHA'
      - '--delivery-pipeline=my-run-demo-app-1'
      - '--region=asia-south1'

  # Step 5: Rollback if deployment fails
  - name: 'google/cloud-sdk:latest'
    id: Rollback on Failure
    entrypoint: 'sh'
    args:
      - -c
      - |
        set -e
        DEPLOYMENT_STATUS=$(gcloud deploy releases describe my-app-1-$SHORT_SHA --delivery-pipeline=my-run-demo-app-1 --region=asia-south1 --format='value(status)')
        if [ "$DEPLOYMENT_STATUS" != "SUCCESS" ]; then
          echo "Deployment failed, rolling back to the previous release..."
          PREV_RELEASE=$(gcloud deploy releases list --delivery-pipeline=my-run-demo-app-1 --region=asia-south1 --sort-by=~createTime --limit=2 --format='value(name)' | tail -n 1)
          gcloud deploy releases create $PREV_RELEASE --delivery-pipeline=my-run-demo-app-1 --region=asia-south1 --skaffold-file=skaffold.yaml
        else
          echo "Deployment succeeded, no rollback needed."
        fi

images:
  - 'asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1:latest'

logsBucket: 'gs://cloud-build-02'
