apiVersion: skaffold/v2beta30
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/infra-samruddh-bharat-poc-01/my-app-01/my-app-1
deploy:
  cloudrun:
    region: asia-south1
    project: infra-samruddh-bharat-poc-01
    service: my-app-service
