apiVersion: skaffold/v2beta30
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: asia-south1-docker.pkg.dev/prajesh/my-app2/my-app-1
deploy:
  kubectl:
    manifests:
    - cloud-run-service
