apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: my-app-1
build:
  artifacts:
  - image: asia-south1-docker.pkg.dev/prajesh/my-app2/my-app-1
    context: .
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    gitCommit:
      variant: SHA
deploy:
  cloudrun:
    region: asia-south1
    projectId: prajesh
    rollout:
      retryOnUpdateConflict: true
    service:
      name: my-app-1
      region: asia-south1
profiles:
  - name: cloudrun
    deploy:
      cloudrun:
        projectId: prajesh
        region: asia-south1
        service:
          name: my-app-1
