apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: myapp
profiles:
- name: dev
  manifests:
    rawYaml:
    - cloud-deploy/dev/dev.yaml
- name: prod
  manifests:
    rawYaml:
    - cloud-deploy/prod/prod.yaml
deploy:
  cloudrun: {}
