apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsdev
description: Cloud Run development service
run:
  location: projects/infra-samruddh-bharat-poc-01/locations/asia-south1
